add_newline = true

[character]
success_symbol = "[âŸ](bold blue) "
error_symbol = "[âœ—](bold red) "

# Hide the username. The username will only show in certain scenarios
[username]
disabled = false

[hostname]
ssh_only = false
format =  "[$hostname](bold #ee00ff) [â¯](bold green) "
trim_at = ".companyname.com"
disabled = false

[directory]
truncation_length = 5
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = " ğŸ”’"
read_only_style = "red"
style = "bold italic blue"

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
format = "[ï‰” $duration](bold yellow)"
style = "bold italic blue"

[docker_context]
format = "[$context](blue bold)"
symbol = 'ïŒˆ '

[kubernetes]
format = 'on [â˜¸ $context \($namespace\)](dimmed green) '
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
".*/openshift-cluster/.*" = "openshift"
"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"

[azure]
symbol = 'ï´ƒ '

[aws]
symbol = "îŒ½ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
symbol = "ï˜ "
truncation_length = 15
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = " ï°– "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[â¯â¯ PICKING](bold red)"

[git_status]
conflicted = '$ {count}âš  '
ahead = " ${count}â˜‹ "
behind = " ${count}â˜Š "
diverged = " âš™${ahead_count}â˜‹ ${behind_count}â˜Š "
untracked = ' ${count}ã€¥ '
stashed = ' ${count}âœ‚ '
modified = ' ${count}âœ '
staged = ' ${count}âš£ '
renamed = ' ${count}âœ‘ '
deleted = ' ${count}âœ˜ '
# up_to_date = 'âœ” '

[hg_branch]
format = "[$branch](bold purple)"
truncation_length = 15
truncation_symbol = ""

[golang]
format = "[î˜§ $version](bold cyan) "

[helm]
format = "[âˆ $version](bold white) "

[java]
symbol = "â™¨ "

[julia]
symbol = "î˜¤ "

[package]
symbol = 'âœ‡ '

[lua]
format = "[î˜  $version](bold blue) "

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[perl]
symbol = "î© "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "î¨ "

[scala]
symbol = "îœ· "

[shlvl]
symbol = "ï„  "

[swift]
symbol = "ï¯£ "

[nodejs]
format = "[îœ˜ $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]
