[shlvl]
disabled = false
threshold = 1
symbol = "â†•ï¸ "

[character]
symbol = "âœ"
success_symbol = "[âœ”](bold green)"
error_symbol = "[âœ—](bold red)"

# Show the current directory
[directory]
truncation_length = 3

[shell]
disabled = false
bash_indicator = "î¯Š"

[git_branch]
symbol = "ğŸŒ¿ "

[git_status]
staged = "[+](green)"
untracked = "[?](red)"
modified = "[*](yellow)"
